[build]
  command = "npm run build"  # Adjust this based on your build script
  publish = "public"

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socket/:splat"
  status = 101
  force = true
